Fix issue#206 and issue#213 By making text bubbles step by step
hackclub/sinerider pull request #269
Opened 2023-03-21 20:18 UTC by Benjamin-Rosenfeld

2023-03-23 17:26 UTC, polytroper commented
Just a heads-up, I renamed TextBubble to Tip. Much shorter and to the point.

Now about your implementation. This technically works but uses some anti-patterns for our engine (and OOP more generally). Namely, it relies on DOM querying/manipulation for state management and communication between Tips instead of keeping that stuff confined to the Entity tree. You could say that your "model" is getting mixed with your "view".

Instead of querying the DOM for the next Tip, each one should be passed a `completeTip` callback from `Level` that activates the next Tip in the sequence. Does that make sense?

2023-03-24 00:08 UTC, Benjamin-Rosenfeld commented
It shoule be better now, please check

2023-03-24 01:03 UTC, polytroper commented
Your code looks mostly good. Let's actually first change some of the code you didn't write.

Let's change `Tip` so that that instead of destroying itself, it just sets an internal "completed" variable. Expose that variable on the `Tip` entity with a read-only property like `get completed() {return completed}`. Create a new method called `refreshDom` that updates the visibility and any other state of the dom node. Create another new method called `complete` that gets called where destroy is called now. `complete()` should:
* Set completed to true
* Call `refreshDom`
* Call `tipCompleted`
Then when `tipCompleted` is called, we loop over every `Tip` in our `Level` and call `refreshDom` on each of them.

Does that make sense?

2023-03-25 00:16 UTC, Benjamin-Rosenfeld commented
Sorry, I forgot to push changes and tried to commit nothing.

2023-03-25 00:46 UTC, Benjamin-Rosenfeld commented
uh oh, I accidently pushed the axis ticks. Can you please roll that back

2023-03-27 18:40 UTC, polytroper requested changes
Looks mostly good, asked for a few subtle changes. My big question about the Axes thing is that I don't see why a separate entity is needed

2023-03-27 18:40 UTC, polytroper commented on Types/Entities/AxesTicks.js
> +function AxesTicks(spec) {
Why is AxesTicks its own entity now? Should just be a part of Axes I think

2023-03-27 22:59 UTC, polytroper approved these changes
Ok merging

2023-03-27 22:59 UTC, merged